MyQTest/Controllers/StudentController.cs
using MyQTest.Models;
using MyQTest.ServiceLayer.Interfaces;
using MyQTest.ServiceLayer.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyQTest.Controllers
{
    public class StudentController : Controller
    {
        IStudentService studentService = new StudentService();
        //
        // GET: /Student/

        public ActionResult Index()
        {
            List<Student> items = studentService.GetStudents();
            return View(items);
        }

        //
        // GET: /Student/Details/5

        public ActionResult Details(Student item)
        {
            return View(item);
        }

        //
        // GET: /Student/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Student/Create

        [HttpPost]
        public ActionResult Create(Student item)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", item);
            }

            studentService.CreateStudent(item);

            return RedirectToAction("Index");
        }

        //
        // GET: /Student/Edit/5

        public ActionResult Edit(int id)
        {
            Student item = studentService.GetStudent(id);
            return View(item);
        }

        //
        // POST: /Student/Edit/5

        [HttpPost]
        public ActionResult Edit(Student item)
        {
            if (!ModelState.IsValid)
            {
                return View("Delete", item);
            }

            studentService.UpdateStudent(item);

            return RedirectToAction("Index");
        }

        //
        // GET: /Student/Delete/5

        public ActionResult Delete(int id)
        {
            Student item = studentService.GetStudent(id);
            return View(item);
        }

        //
        // POST: /Student/Delete/5

        [HttpPost]
        public ActionResult Delete(Student item)
        {
            if (!ModelState.IsValid)
            {
                return View("Delete", item);
            }

            studentService.RemoveStudent(item);

            return RedirectToAction("Index");
        }
    }
}

MyQTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("MyQTest", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Students", "Index", "Student")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Inga Cigoj</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>